### ISSUE TITLE
Upgrade with YNH3.8 failed

### ISSUE THREAD

**Issue by gnouts** [YunoHost-Apps/funkwhale_ynh#108]
Hi,
I did a system upgrade which installed me [ynh v3.8](https://forum.yunohost.org/t/yunohost-3-8-release-sortie-de-yunohost-3-8/11527), then upgrade my apps, but Funkwhale failed.

Here is the relevant stacktrace :
```
Info: Upgrading dependencies...
Info: Making sure dedicated system user exists...
Warning:   Running command git clone -q https://github.com/EliotBerriot/requests-http-signature.git /tmp/pip-req-build-ofhcn8ct
Warning:   Running command git checkout -b signature-header-support --track origin/signature-header-support
Warning:   Switched to a new branch 'signature-header-support'
Warning:   Branch signature-header-support set up to track remote branch signature-header-support from origin.
Warning: ERROR: channels-redis 2.2.1 has requirement asgiref~=2.1, but you'll have asgiref 3.2.7 which is incompatible.
Warning: 2020-05-21 13:51:31,521 funkwhale_api.config INFO     Loaded env file at /var/www/funkwhale/code/config/.env
Warning: 2020-05-21 13:51:31,521 funkwhale_api.config INFO     Running with no plugins
Warning: Traceback (most recent call last):
Warning:   File "api/manage.py", line 27, in <module>
Warning:     execute_from_command_line(sys.argv)
Warning:   File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
Warning:     utility.execute()
Warning:   File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
Warning:     self.fetch_command(subcommand).run_from_argv(self.argv)
Warning:   File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/django/core/management/base.py", line 323, in run_from_argv
Warning:     self.execute(*args, **cmd_options)
Warning:   File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/django/core/management/base.py", line 364, in execute
Warning:     output = self.handle(*args, **options)
Warning:   File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/django/core/management/base.py", line 83, in wrapped
Warning:     res = handle_func(*args, **kwargs)
Warning:   File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 234, in handle
Warning:     fake_initial=fake_initial,
Warning:   File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 117, in migrate
Warning:     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
Warning:   File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
Warning:     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
Warning:   File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 245, in apply_migration
Warning:     state = migration.apply(state, schema_editor)
Warning:   File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/django/db/migrations/migration.py", line 124, in apply
Warning:     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
Warning:   File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
Warning:     self.code(from_state.apps, schema_editor)
Warning:   File "/var/www/funkwhale/code/api/funkwhale_api/music/migrations/0043_album_cover_attachment.py", line 18, in create_attachments
Warning:     print('Creating attachments for {} album covers, this may take a while\u2026'.format(total))
Warning: UnicodeEncodeError: 'ascii' codec can't encode character '\u2026' in position 65: ordinal not in range(128)
Warning: [ERR] Upgrade failed.
```
Rollback was not triggered and funkwhale appeared to be broken.
I used to have a symlink in `/var/ww/funkwhale/media` pointing to `/home/yunohost.app/funkwhale` and it was removed. Recreating the symlink make funkwhale work again but I'm still using the old version.

**Comment by Sporiff** [comment]
I think this is the same thing I experienced in #106. After rebooting the system, I was able to install, upgrade, and do everything with no issues, but something is definitely causing a problem. The fact that the rollback is not triggered is troubling and is one of the reasons I'm keen to progress with #15.
