### ISSUE TITLE
The funkwhale-beat service won't start

### ISSUE THREAD

**Issue by MyNameIsTroll** [YunoHost-Apps/funkwhale_ynh#111]
Hi everybody,
I came to see you because of a little problem I'm having with the Funkwhale app.

_My Material: Raspberry Pi 3 (ARM)
YunoHost version: 3.8.4.8 (stable)._

When I restart my server because my ISP changed my IP address, I can't get the **funkwhale-beat** service running again.
All the other services work correctly.

I tried to restart it first via the web interface, it launches but 2 minutes later its status becomes "failed" again. and then on the command line ( **yunohost service start funkwhale-beat** ). But unfortunately nothing.
I don't know if anyone has encountered this problem before, maybe you have an idea where it can come from.

This is what my JournalCtl tells me:

```
Jun 12 00:40:44 funkwhale-beat[4072]: 2020-06-12 00:40:44,859 funkwhale_api.config INFO     Loaded env file at /var/www/funkwhale/code/config/.env
Jun 12 00:40:44 funkwhale-beat[4072]: 2020-06-12 00:40:44,877 funkwhale_api.config INFO     Running with no plugins
Jun 12 00:41:06 funkwhale-beat[4072]: celery beat v4.3.0 (rhubarb) is starting.
Jun 12 00:41:06 funkwhale-beat[4072]: __    -    ... __   -        _
Jun 12 00:41:06 funkwhale-beat[4072]: LocalTime -> 2020-06-11 22:41:05
Jun 12 00:41:06 funkwhale-beat[4072]: Configuration ->
Jun 12 00:41:06 funkwhale-beat[4072]:     . broker -> redis://127.0.0.1:6379/0
Jun 12 00:41:06 funkwhale-beat[4072]:     . loader -> celery.loaders.app.AppLoader
Jun 12 00:41:06 funkwhale-beat[4072]:     . scheduler -> celery.beat.PersistentScheduler
Jun 12 00:41:06 funkwhale-beat[4072]:     . db -> celerybeat-schedule
Jun 12 00:41:06 funkwhale-beat[4072]:     . logfile -> /var/log/funkwhale/beat.log@%INFO
Jun 12 00:41:06 funkwhale-beat[4072]:     . maxinterval -> 5.00 minutes (300s)
Jun 12 00:41:06 systemd[1]: funkwhale-beat.service: Main process exited, code=exited, status=1/FAILURE
Jun 12 00:41:06 systemd[1]: funkwhale-beat.service: Unit entered failed state.
Jun 12 00:41:06 systemd[1]: funkwhale-beat.service: Failed with result 'exit-code'.

```

**Comment by Thovi98** [comment]
I have the same problem, but it doesn’t appear to have an impact because I can continue to listen without issue all of my tracks. I have exactly the same journalctl than above, and my logs are :

```
mand)
[2020-06-18 07:09:01,622: WARNING/MainProcess] File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/celery/bin/base.py", line 386, in handle_argv
[2020-06-18 07:09:01,622: WARNING/MainProcess] return self(*args, **options)
[2020-06-18 07:09:01,623: WARNING/MainProcess] File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/celery/bin/base.py", line 252, in __call__
[2020-06-18 07:09:01,623: WARNING/MainProcess] ret = self.run(*args, **kwargs)
[2020-06-18 07:09:01,623: WARNING/MainProcess] File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/celery/bin/beat.py", line 109, in run
[2020-06-18 07:09:01,623: WARNING/MainProcess] return beat().run()
[2020-06-18 07:09:01,623: WARNING/MainProcess] File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/celery/apps/beat.py", line 81, in run
[2020-06-18 07:09:01,624: WARNING/MainProcess] self.start_scheduler()
[2020-06-18 07:09:01,624: WARNING/MainProcess] File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/celery/apps/beat.py", line 109, in start_scheduler
[2020-06-18 07:09:01,624: WARNING/MainProcess] service.start()
[2020-06-18 07:09:01,624: WARNING/MainProcess] File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/celery/beat.py", line 588, in start
[2020-06-18 07:09:01,625: WARNING/MainProcess] humanize_seconds(self.scheduler.max_interval))
[2020-06-18 07:09:01,625: WARNING/MainProcess] File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/kombu/utils/objects.py", line 44, in __get__
[2020-06-18 07:09:01,625: WARNING/MainProcess] value = obj.__dict__[self.__name__] = self.__get(obj)
[2020-06-18 07:09:01,625: WARNING/MainProcess] File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/celery/beat.py", line 632, in scheduler
[2020-06-18 07:09:01,626: WARNING/MainProcess] return self.get_scheduler()
[2020-06-18 07:09:01,626: WARNING/MainProcess] File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/celery/beat.py", line 627, in get_scheduler
[2020-06-18 07:09:01,627: WARNING/MainProcess] lazy=lazy,
[2020-06-18 07:09:01,627: WARNING/MainProcess] File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/celery/beat.py", line 467, in __init__
[2020-06-18 07:09:01,627: WARNING/MainProcess] Scheduler.__init__(self, *args, **kwargs)
[2020-06-18 07:09:01,627: WARNING/MainProcess] File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/celery/beat.py", line 226, in __init__
[2020-06-18 07:09:01,628: WARNING/MainProcess] self.setup_schedule()
[2020-06-18 07:09:01,628: WARNING/MainProcess] File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/celery/beat.py", line 495, in setup_schedule
[2020-06-18 07:09:01,628: WARNING/MainProcess] self._create_schedule()
[2020-06-18 07:09:01,628: WARNING/MainProcess] File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/celery/beat.py", line 528, in _create_schedule
[2020-06-18 07:09:01,629: WARNING/MainProcess] self._store[str('entries')] = {}
[2020-06-18 07:09:01,629: WARNING/MainProcess] File "/usr/lib/python3.5/shelve.py", line 125, in __setitem__
[2020-06-18 07:09:01,629: WARNING/MainProcess] self.dict[key.encode(self.keyencoding)] = f.getvalue()
[2020-06-18 07:09:01,630: WARNING/MainProcess] _dbm
[2020-06-18 07:09:01,630: WARNING/MainProcess] .
[2020-06-18 07:09:01,630: WARNING/MainProcess] error
[2020-06-18 07:09:01,630: WARNING/MainProcess] :
[2020-06-18 07:09:01,630: WARNING/MainProcess] cannot add item to database
[2020-06-18 07:09:01,836: WARNING/MainProcess] Exception ignored in:
[2020-06-18 07:09:01,836: WARNING/MainProcess] <bound method Shelf.__del__ of <shelve.DbfilenameShelf object at 0x7f48ffe5c2b0>>
[2020-06-18 07:09:01,837: WARNING/MainProcess] Traceback (most recent call last):
[2020-06-18 07:09:01,837: WARNING/MainProcess] File "/usr/lib/python3.5/shelve.py", line 162, in __del__
[2020-06-18 07:09:01,838: WARNING/MainProcess] self.close()
[2020-06-18 07:09:01,838: WARNING/MainProcess] File "/usr/lib/python3.5/shelve.py", line 144, in close
[2020-06-18 07:09:01,838: WARNING/MainProcess] self.sync()
[2020-06-18 07:09:01,838: WARNING/MainProcess] File "/usr/lib/python3.5/shelve.py", line 168, in sync
[2020-06-18 07:09:01,839: WARNING/MainProcess] self[key] = entry
[2020-06-18 07:09:01,839: WARNING/MainProcess] File "/usr/lib/python3.5/shelve.py", line 125, in __setitem__
[2020-06-18 07:09:01,840: WARNING/MainProcess] self.dict[key.encode(self.keyencoding)] = f.getvalue()
[2020-06-18 07:09:01,840: WARNING/MainProcess] _dbm
[2020-06-18 07:09:01,840: WARNING/MainProcess] .
[2020-06-18 07:09:01,840: WARNING/MainProcess] error
[2020-06-18 07:09:01,840: WARNING/MainProcess] :
[2020-06-18 07:09:01,841: WARNING/MainProcess] cannot add item to database
```

**Comment by Josue-T** [comment]
Hello,

I fixed this issue by this command:
```
mv /var/www/funkwhale/code/api/celerybeat-schedule.db /var/www/funkwhale/code/api/celerybeat-schedule_old.db
```
This just leave funkwhale to recreate this file.

**Comment by Thovi98** [comment]
Thanks @Josue-T !
I confirm, it works, my funkwhale-beat service now runs fine !!

**Comment by MyNameIsTroll** [comment]
Thank you for your answers and help.
Unfortunately I can't try anymore because I installed buster and redo a complete installation of funkwhale.
But it might be useful for others.

**Comment by lightnin** [comment]
I have the same issue, logs here: https://paste.yunohost.org/usewusugir

The fix mentioned above:
https://github.com/YunoHost-Apps/funkwhale_ynh/issues/111#issuecomment-705200932
Worked for me as well, at least for now.

**Comment by lightnin** [comment]
After a backup and restore onto new sd card, this issue appeared for me again. Followed steps in #111 and it again appears to have fixed the issue for me. Note that the package has been upgraded between when I last did this fix and this restore / fix again.
