### ISSUE TITLE
502 Bad Gateway since migration to Buster

### ISSUE THREAD

**Issue by Thovi98** [YunoHost-Apps/funkwhale_ynh#114]
Since migration to Buster, I cannot use Funkwhale anymore. On any web browser it shows `502 Bad Gateway - nginx`, and on Android via Otter, it doesn’t say anything but I can’t play not downloaded tracks.

In my Yunohost webadmin, I see that none of my funkwhale services works...
`funkwhale-beat` doesn’t work for a while (see https://github.com/YunoHost-Apps/funkwhale_ynh/issues/111), but it didn’t affect my user experience, since all worked good. 

But now, `funkwhale-server` doesn’t work anymore too :

Journalctl 

```
-- Logs begin at Thu 2020-07-30 11:32:45 CEST, end at Thu 2020-07-30 15:01:56 CEST. --
jui 30 11:33:28 systemd[1]: Started Funkwhale (funkwhale) application server.
-- Subject: L'unité (unit) funkwhale-server.service a terminé son démarrage
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- L'unité (unit) funkwhale-server.service a terminé son démarrage, avec le résultat done.
jui 30 11:33:30 funkwhale-server[1435]: Could not find platform independent libraries <prefix>
jui 30 11:33:30 funkwhale-server[1435]: Could not find platform dependent libraries <exec_prefix>
jui 30 11:33:30 funkwhale-server[1435]: Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
jui 30 11:33:30 funkwhale-server[1435]: Fatal Python error: Py_Initialize: Unable to get the locale encoding
jui 30 11:33:30 funkwhale-server[1435]: ImportError: No module named 'encodings'
jui 30 11:33:30 funkwhale-server[1435]: Current thread 0x00007f1127ce9740 (most recent call first):
jui 30 11:33:30 systemd[1]: funkwhale-server.service: Main process exited, code=killed, status=6/ABRT
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- An ExecStart= process belonging to unit funkwhale-server.service has exited.
-- 
-- The process' exit code is 'killed' and its exit status is 6.
jui 30 11:33:30 systemd[1]: funkwhale-server.service: Failed with result 'signal'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit funkwhale-server.service has entered the 'failed' state with result 'signal'.
```

Nor `funkwhale-worker` : 

Journalctl 

```
-- Logs begin at Thu 2020-07-30 11:32:45 CEST, end at Thu 2020-07-30 15:03:14 CEST. --
jui 30 11:33:28 systemd[1]: Started Funkwhale (funkwhale) celery worker.
-- Subject: L'unité (unit) funkwhale-worker.service a terminé son démarrage
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- L'unité (unit) funkwhale-worker.service a terminé son démarrage, avec le résultat done.
jui 30 11:33:30 funkwhale-worker[1433]: Could not find platform independent libraries <prefix>
jui 30 11:33:30 funkwhale-worker[1433]: Could not find platform dependent libraries <exec_prefix>
jui 30 11:33:30 funkwhale-worker[1433]: Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
jui 30 11:33:30 funkwhale-worker[1433]: Fatal Python error: Py_Initialize: Unable to get the locale encoding
jui 30 11:33:30 funkwhale-worker[1433]: ImportError: No module named 'encodings'
jui 30 11:33:30 funkwhale-worker[1433]: Current thread 0x00007f328ffa9740 (most recent call first):
jui 30 11:33:30 systemd[1]: funkwhale-worker.service: Main process exited, code=killed, status=6/ABRT
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- An ExecStart= process belonging to unit funkwhale-worker.service has exited.
-- 
-- The process' exit code is 'killed' and its exit status is 6.
jui 30 11:33:30 systemd[1]: funkwhale-worker.service: Failed with result 'signal'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit funkwhale-worker.service has entered the 'failed' state with result 'signal'.
```

/var/log/funkwhale/worker.log

```
[2020-07-28 10:23:25,764: INFO/ForkPoolWorker-1] Task music.process_upload[211d0088-49a5-4b92-b55a-d23fbbc24ba6] succeeded in 0.3301509249722585s: None
[2020-07-28 10:23:26,504: INFO/MainProcess] Received task: music.process_upload[dc4c3724-8d7b-4510-99ab-3f59bc76a2b1]  
[2020-07-28 10:23:26,828: INFO/ForkPoolWorker-1] Task music.process_upload[dbd6e5a2-e959-4fbe-931d-618263093e45] succeeded in 0.3229991199914366s: None
[2020-07-28 10:23:29,263: INFO/ForkPoolWorker-1] Task music.process_upload[dc4c3724-8d7b-4510-99ab-3f59bc76a2b1] succeeded in 1.322529370081611s: None
[2020-07-28 10:23:29,627: INFO/MainProcess] Received task: music.process_upload[99160046-f8c6-4ae8-beaf-0baf9eda066f]  
[2020-07-28 10:23:30,037: INFO/ForkPoolWorker-1] Task music.process_upload[99160046-f8c6-4ae8-beaf-0baf9eda066f] succeeded in 0.4051989340223372s: None
[2020-07-28 10:23:30,763: INFO/MainProcess] Received task: music.process_upload[afabb99b-d89b-4497-bd3c-58ee846f3387]  
[2020-07-28 10:23:31,043: INFO/ForkPoolWorker-1] Task music.process_upload[afabb99b-d89b-4497-bd3c-58ee846f3387] succeeded in 0.27827389899175614s: None
[2020-07-28 10:23:31,852: INFO/MainProcess] Received task: music.process_upload[db910d83-d7e9-4240-bb9e-b1ca750b84af]  
[2020-07-28 10:23:32,157: INFO/ForkPoolWorker-1] Task music.process_upload[db910d83-d7e9-4240-bb9e-b1ca750b84af] succeeded in 0.30211962398607284s: None
[2020-07-28 10:23:35,594: INFO/MainProcess] Received task: music.process_upload[6960a683-b596-47b3-b786-d548fdd5e5f4]  
[2020-07-28 10:23:35,764: INFO/ForkPoolWorker-1] Task music.process_upload[6960a683-b596-47b3-b786-d548fdd5e5f4] succeeded in 0.16806725098285824s: None
[2020-07-28 10:23:36,651: INFO/MainProcess] Received task: music.process_upload[1228e270-c372-4120-9b0e-418e09cff1b1]  
[2020-07-28 10:23:36,875: INFO/ForkPoolWorker-1] Task music.process_upload[1228e270-c372-4120-9b0e-418e09cff1b1] succeeded in 0.22214662202168256s: None
[2020-07-28 10:23:37,640: INFO/MainProcess] Received task: music.process_upload[02297dc3-3c33-404e-868b-2457e0434a6b]  
[2020-07-28 10:23:38,735: INFO/ForkPoolWorker-1] Task music.process_upload[02297dc3-3c33-404e-868b-2457e0434a6b] succeeded in 0.18574562401045114s: None
[2020-07-29 20:18:33,718: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/kombu/transport/redis.py", line 1052, in on_readable
    self.cycle.on_readable(fileno)
  File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/kombu/transport/redis.py", line 348, in on_readable
    chan.handlers[type]()
  File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/kombu/transport/redis.py", line 679, in _receive
    ret.append(self._receive_one(c))
  File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/kombu/transport/redis.py", line 690, in _receive_one
    response = c.parse_response()
  File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/redis/client.py", line 3453, in parse_response
    response = self._execute(conn, conn.read_response)
  File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/redis/client.py", line 3427, in _execute
    return command(*args, **kwargs)
  File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/redis/connection.py", line 734, in read_response
    response = self._parser.read_response()
  File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/redis/connection.py", line 463, in read_response
    self.read_from_socket()
  File "/var/www/funkwhale/code/virtualenv/lib/python3.5/site-packages/redis/connection.py", line 422, in read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
[2020-07-29 20:18:39,217: INFO/MainProcess] Connected to redis://127.0.0.1:6379/1
[2020-07-29 20:18:39,237: INFO/MainProcess] mingle: searching for neighbors
[2020-07-29 20:18:40,269: INFO/MainProcess] mingle: all alone
```

I would love to see this package work again, I use it a lot and with joy 😃

**Comment by artus40** [comment]
Hi !

I had the same problem and it seems it's due to a broken virtualenv.

I created a new one following steps from [install script](https://github.com/YunoHost-Apps/funkwhale_ynh/blob/master/scripts/install#L120), rebooted the server and now it seems to work.

Here is what I did in my case : 

1. Go to install folder
$ cd /var/www/funkwhale/code

2. Backup old virtualenv
$ sudo -u funkwhale mv virtualenv virtualenv.old

3. Create a new one
$ sudo -u funkwhale virtualenv -p python3 virtualenv

4. Give write permissions to any user (temporary)
$ sudo chmod -R o+w virtualenv

5. Configure the new virtual env
$ source virtualenv/bin/activate
(virtualenv) $ pip install wheels
(virtualenv) $ pip install api/requirements.txt
(virtualenv) $ deactivate

6. Remove write permissions
$ sudo chmod -R o-w virtualenv

You can check out if it works by starting funkwhale-beat service
$ sudo service funkwhale-beat start
$ sudo service funkwhale-beat status

If it's good, reboot (simplest way to restart everything :)
$ sudo yunohost tools reboot

Hope it works for you too!

**Comment by Thovi98** [comment]
Thanks for your help !

But it didn’t luck for me.

`(virtualenv) $ pip install wheels` reported an error, that cannot fulfill the requirements, but with `(virtualenv) $ pip install wheel` there was no error. 

`(virtualenv) $ pip install api/requirements.txt` says it is a directory, so nothing change.

At the end it couldn’t help start the services. Thanks anyway 😄

**Comment by artus40** [comment]
Hi !

Oups, my bad. 

It is indeed $ pip install wheel, without s
And for the requirements installation, i forgot to the -r option !
Try :
$ pip install -r /var/www/funkwhale/code/api/requirements.txt
from inside the virtual env and it should work !

**Comment by Thovi98** [comment]
Amazing, it works fine now !
I have still the funkwhale-beat problem (https://github.com/YunoHost-Apps/funkwhale_ynh/issues/111), but it doesn’t affect the user experience.

The 2 other services work perfectly now, thanks !!!

**Comment by jmbmkn** [comment]
I'm trying to use this fix, but my server will not let my admin user execute commands as the funkwhale user. What am I missing?

**Comment by Thovi98** [comment]
Since update to 1.0 is stable and officially supports Buster, I think I can close this issue.
