### ISSUE TITLE
Install fails on ARM ?

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/funkwhale_ynh#13]
Hellow,

currently trying to install funkwhale on an Internet Cube (Lime 1)

I see the following error which is related to zlib (I guess installing the right header package should do the trick)

```
1056220 WARNING   Failed building wheel for Pillow
1056222 INFO   creating build/lib.linux-armv7l-3.5
1056224 INFO   creating build/lib.linux-armv7l-3.5/PIL
1056227 INFO   copying PIL/PngImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056230 INFO   copying PIL/ImageGrab.py -> build/lib.linux-armv7l-3.5/PIL
1056234 INFO   copying PIL/BdfFontFile.py -> build/lib.linux-armv7l-3.5/PIL
1056238 INFO   copying PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056245 INFO   copying PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056250 INFO   copying PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056254 INFO   copying PIL/GifImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056266 INFO   copying PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056271 INFO   copying PIL/_util.py -> build/lib.linux-armv7l-3.5/PIL
1056278 INFO   copying PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056285 INFO   copying PIL/ImageTransform.py -> build/lib.linux-armv7l-3.5/PIL
1056289 INFO   copying PIL/SunImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056294 INFO   copying PIL/PyAccess.py -> build/lib.linux-armv7l-3.5/PIL
1056300 INFO   copying PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056305 INFO   copying PIL/ImageSequence.py -> build/lib.linux-armv7l-3.5/PIL
1056313 INFO   copying PIL/ImageFont.py -> build/lib.linux-armv7l-3.5/PIL
1056319 INFO   copying PIL/ImageCms.py -> build/lib.linux-armv7l-3.5/PIL
1056326 INFO   copying PIL/ImagePalette.py -> build/lib.linux-armv7l-3.5/PIL
1056331 INFO   copying PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056337 INFO   copying PIL/ExifTags.py -> build/lib.linux-armv7l-3.5/PIL
1056343 INFO   copying PIL/OleFileIO.py -> build/lib.linux-armv7l-3.5/PIL
1056349 INFO   copying PIL/ImageMode.py -> build/lib.linux-armv7l-3.5/PIL
1056354 INFO   copying PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056360 INFO   copying PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056366 INFO   copying PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056372 INFO   copying PIL/ImageQt.py -> build/lib.linux-armv7l-3.5/PIL
1056378 INFO   copying PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056384 INFO   copying PIL/TiffTags.py -> build/lib.linux-armv7l-3.5/PIL
1056390 INFO   copying PIL/features.py -> build/lib.linux-armv7l-3.5/PIL
1056396 INFO   copying PIL/ContainerIO.py -> build/lib.linux-armv7l-3.5/PIL
1056402 INFO   copying PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056408 INFO   copying PIL/ImageFile.py -> build/lib.linux-armv7l-3.5/PIL
1056414 INFO   copying PIL/__init__.py -> build/lib.linux-armv7l-3.5/PIL
1056420 INFO   copying PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056426 INFO   copying PIL/ImagePath.py -> build/lib.linux-armv7l-3.5/PIL
1056431 INFO   copying PIL/ImageDraw2.py -> build/lib.linux-armv7l-3.5/PIL
1056437 INFO   copying PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056443 INFO   copying PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056449 INFO   copying PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056456 INFO   copying PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056462 INFO   copying PIL/WalImageFile.py -> build/lib.linux-armv7l-3.5/PIL
1056467 INFO   copying PIL/ImageStat.py -> build/lib.linux-armv7l-3.5/PIL
1056472 INFO   copying PIL/Image.py -> build/lib.linux-armv7l-3.5/PIL
1056478 INFO   copying PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056485 INFO   copying PIL/CurImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056491 INFO   copying PIL/ImImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056497 INFO   copying PIL/TarIO.py -> build/lib.linux-armv7l-3.5/PIL
1056503 INFO   copying PIL/ImageFilter.py -> build/lib.linux-armv7l-3.5/PIL
1056509 INFO   copying PIL/GdImageFile.py -> build/lib.linux-armv7l-3.5/PIL
1056515 INFO   copying PIL/ImageEnhance.py -> build/lib.linux-armv7l-3.5/PIL
1056521 INFO   copying PIL/ImageShow.py -> build/lib.linux-armv7l-3.5/PIL
1056527 INFO   copying PIL/MicImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056533 INFO   copying PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056538 INFO   copying PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056544 INFO   copying PIL/ImageColor.py -> build/lib.linux-armv7l-3.5/PIL
1056551 INFO   copying PIL/ImageMath.py -> build/lib.linux-armv7l-3.5/PIL
1056557 INFO   copying PIL/FliImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056562 INFO   copying PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056568 INFO   copying PIL/_tkinter_finder.py -> build/lib.linux-armv7l-3.5/PIL
1056574 INFO   copying PIL/ImageTk.py -> build/lib.linux-armv7l-3.5/PIL
1056581 INFO   copying PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056586 INFO   copying PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056592 INFO   copying PIL/PSDraw.py -> build/lib.linux-armv7l-3.5/PIL
1056598 INFO   copying PIL/ImageWin.py -> build/lib.linux-armv7l-3.5/PIL
1056603 INFO   copying PIL/ImageOps.py -> build/lib.linux-armv7l-3.5/PIL
1056610 INFO   copying PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056615 INFO   copying PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056621 INFO   copying PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-3.5/PIL
1056627 INFO   copying PIL/GimpGradientFile.py -> build/lib.linux-armv7l-3.5/PIL
1056632 INFO   copying PIL/ImageDraw.py -> build/lib.linux-armv7l-3.5/PIL
1056639 INFO   copying PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056642 INFO   copying PIL/ImageChops.py -> build/lib.linux-armv7l-3.5/PIL
1056648 INFO   copying PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056654 INFO   copying PIL/version.py -> build/lib.linux-armv7l-3.5/PIL
1056660 INFO   copying PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056667 INFO   copying PIL/JpegPresets.py -> build/lib.linux-armv7l-3.5/PIL
1056673 INFO   copying PIL/ImageMorph.py -> build/lib.linux-armv7l-3.5/PIL
1056677 INFO   copying PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056684 INFO   copying PIL/FontFile.py -> build/lib.linux-armv7l-3.5/PIL
1056688 INFO   copying PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056695 INFO   copying PIL/MspImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056699 INFO   copying PIL/_binary.py -> build/lib.linux-armv7l-3.5/PIL
1056704 INFO   copying PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056709 INFO   copying PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056713 INFO   copying PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056716 INFO   copying PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056720 INFO   copying PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056723 INFO   copying PIL/PcfFontFile.py -> build/lib.linux-armv7l-3.5/PIL
1056727 INFO   copying PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-3.5/PIL
1056731 INFO   copying PIL/PaletteFile.py -> build/lib.linux-armv7l-3.5/PIL
1056735 INFO   running egg_info
1056738 INFO   writing Pillow.egg-info/PKG-INFO
1056743 INFO   writing requirements to Pillow.egg-info/requires.txt
1056745 INFO   writing top-level names to Pillow.egg-info/top_level.txt
1056750 INFO   writing dependency_links to Pillow.egg-info/dependency_links.txt
1056754 INFO   reading manifest file 'Pillow.egg-info/SOURCES.txt'
1056758 INFO   reading manifest template 'MANIFEST.in'
1056762 INFO   warning: no files found matching '*.sh'
1056765 INFO   no previously-included directories found matching 'docs/_static'
1056769 INFO   warning: no previously-included files found matching '.coveragerc'
1056772 INFO   warning: no previously-included files found matching 'codecov.yml'
1056775 INFO   warning: no previously-included files found matching '.editorconfig'
1056779 INFO   warning: no previously-included files found matching '.landscape.yaml'
1056784 INFO   warning: no previously-included files found matching '.travis'
1056788 INFO   warning: no previously-included files found matching '.travis/*'
1056792 INFO   warning: no previously-included files found matching 'appveyor.yml'
1056796 INFO   warning: no previously-included files found matching 'build_children.sh'
1056799 INFO   warning: no previously-included files found matching 'tox.ini'
1056802 INFO   warning: no previously-included files matching '.git*' found anywhere in distribution
1056806 INFO   warning: no previously-included files matching '*.pyc' found anywhere in distribution
1056810 INFO   warning: no previously-included files matching '*.so' found anywhere in distribution
1056814 INFO   writing manifest file 'Pillow.egg-info/SOURCES.txt'
1056818 INFO   running build_ext
1056822 INFO 
1056826 INFO 
1056829 INFO   The headers or library files could not be found for zlib,
1056833 INFO   a required dependency when compiling Pillow from source.
1056836 INFO 
1056839 INFO   Please see the install instructions at:
1056843 INFO      https://pillow.readthedocs.io/en/latest/installation.html
1056847 INFO 
1056852 INFO   Traceback (most recent call last):
1056856 INFO     File "/tmp/pip-install-hhqpx1uf/Pillow/setup.py", line 787, in <module>
1056859 INFO       zip_safe=not (debug_build() or PLATFORM_MINGW), )
1056862 INFO     File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/setuptools/__init__.py", line 129, in setup
1056866 INFO       return distutils.core.setup(**attrs)
1056870 INFO     File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
1056874 INFO       dist.run_commands()
1056877 INFO     File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
1056880 INFO       self.run_command(cmd)
1056884 INFO     File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
1056888 INFO       cmd_obj.run()
1056891 INFO     File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 202, in run
1056897 INFO       self.run_command('build')
1056901 INFO     File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
1056903 INFO       self.distribution.run_command(command)
1056907 INFO     File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
1056910 INFO       cmd_obj.run()
1056914 INFO     File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
1056918 INFO       self.run_command(cmd_name)
1056921 INFO     File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
1056926 INFO       self.distribution.run_command(command)
1056929 INFO     File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
1056934 INFO       cmd_obj.run()
1056938 INFO     File "/usr/lib/python3.5/distutils/command/build_ext.py", line 339, in run
1056941 INFO       self.build_extensions()
1056945 INFO     File "/tmp/pip-install-hhqpx1uf/Pillow/setup.py", line 577, in build_extensions
1056948 INFO       raise RequiredDependencyException(f)
1056952 INFO   __main__.RequiredDependencyException: zlib
1056954 INFO 
1056958 INFO   During handling of the above exception, another exception occurred:
1056961 INFO 
1056964 INFO   Traceback (most recent call last):
1056966 INFO     File "<string>", line 1, in <module>
1056970 INFO     File "/tmp/pip-install-hhqpx1uf/Pillow/setup.py", line 799, in <module>
1056975 INFO       raise RequiredDependencyException(msg)
1056979 INFO   __main__.RequiredDependencyException:
1056983 INFO 
1056986 INFO   The headers or library files could not be found for zlib,
1056990 INFO   a required dependency when compiling Pillow from source.
1056994 INFO 
1056998 INFO   Please see the install instructions at:
1057002 INFO      https://pillow.readthedocs.io/en/latest/installation.html
1057006 INFO 
1057009 INFO 
1057013 INFO 
```

**Comment by alexAubin** [comment]
Installing the following packages seem to have done the trick (got some similar errors for other things) : 

```
apt-get install zlib1g-dev libffi-dev libssl-dev
```

**Comment by Jibec** [comment]
Thanks Alex, I don't have arm to test this :)
BTW, can you please accept the community list PR?

**Comment by Jibec** [comment]
Should be fixed by this commit: https://github.com/YunoHost-Apps/funkwhale_ynh/commit/227c72ffa13f315e07043381bc0dc098f3736367

please test and confirm it works fine for you
