### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/funkwhale_ynh#14]
Hi
Fresh install fails on the vps. I am debian stretch.

```
+ sudo --login --user=postgres psql
ALTER ROLE
+ python api/manage.py migrate
Warning: Traceback (most recent call last):
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
Warning:     self.connect()
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 194, in connect
Warning:     self.connection = self.get_new_connection(conn_params)
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 168, in get_new_connection
Warning:     connection = Database.connect(**conn_params)
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/psycopg2/__init__.py", line 130, in connect
Warning:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Warning: psycopg2.OperationalError: FATAL:  Peer authentication failed for user "funkwhale"
Warning: 
Warning: 
Warning: The above exception was the direct cause of the following exception:
Warning: 
Warning: Traceback (most recent call last):
Warning:   File "api/manage.py", line 20, in <module>
Warning:     execute_from_command_line(sys.argv)
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
Warning:     utility.execute()
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
Warning:     self.fetch_command(subcommand).run_from_argv(self.argv)
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
Warning:     self.execute(*args, **cmd_options)
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
Warning:     output = self.handle(*args, **options)
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 79, in handle
Warning:     executor = MigrationExecutor(connection, self.migration_progress_callback)
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 18, in __init__
Warning:     self.loader = MigrationLoader(self.connection)
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/migrations/loader.py", line 49, in __init__
Warning:     self.build_graph()
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/migrations/loader.py", line 206, in build_graph
Warning:     self.applied_migrations = recorder.applied_migrations()
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
Warning:     if self.has_table():
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 44, in has_table
Warning:     return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 255, in cursor
Warning:     return self._cursor()
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 232, in _cursor
Warning:     self.ensure_connection()
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
Warning:     self.connect()
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
Warning:     raise dj_exc_value.with_traceback(traceback) from exc_value
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
Warning:     self.connect()
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 194, in connect
Warning:     self.connection = self.get_new_connection(conn_params)
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 168, in get_new_connection
Warning:     connection = Database.connect(**conn_params)
Warning:   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/psycopg2/__init__.py", line 130, in connect
Warning:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
Warning: django.db.utils.OperationalError: FATAL:  Peer authentication failed for user "funkwhale"
Warning: 
+ ynh_exit_properly
Warning: !!
Warning:   funkwhale's script has encountered an error. Its execution was cancelled.

```

**Comment by Jibec** [comment]
Weird error message, did you try again?
It looks like the funkwhale user doesn't have access to the postgres database. The remove script will delete the existing user. So a fresh install should create a new user.

Can you tell me the result?

Btw, what's the funkwhale version you're installing? You can see it in the log, where it downloads the archive.

**Comment by anmol26s** [comment]
I have tried many times with same result. I am using the master branch.
The logs  vanishes as installation is long. How can I see full logs?

**Comment by Jibec** [comment]
You can look into /var/log/yunohost
Can you please provide more details about your configuration?

**Comment by anmol26s** [comment]
My architecture details:
`3.16.0-5-amd64 #  SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux
`
```
yunohost -v
yunohost: 
  repo: stable
  version: 3.0.0.1
yunohost-admin: 
  repo: stable
  version: 3.0.0
moulinette: 
  repo: stable
  version: 3.0.0
ssowat: 
  repo: stable
  version: 3.0.0

```

The log is very long , the main part after which the error occurs is already given above.
I am even getting warning on **apt-get update** : 
`W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/backports.list:1 and /etc/apt/sources.list.d/jessie-backports.list:1
`

**Comment by Jibec** [comment]
Interesting, what's the result of 'yunohost app map' ? (You can replace domain names)

**Comment by anmol26s** [comment]
I have lot of apps. But there is no FunkWhale. Domain is free too on which I am trying to install the FunkWhale.

**Comment by Jibec** [comment]
The issue looks like to be in /etc/postgresql/9.6/main/pg_hba.conf

You should have: local all all password
And I think you still have the old content: local all all peer
It's one of the helper action to change this.

Can you tell me what other application us using postgres and if they were installed before or after your migration to 3.0?

**Comment by anmol26s** [comment]
Yes, I was having local all all peer and now I have changed it to local all all password.
I have mastodon and peertube installed, which uses postgres. Both were installed before the migration to 3.0.

**Comment by anmol26s** [comment]
It works now. Thanks for the solution and the app.
