### ISSUE TITLE
Service funkwhale-beat failed

### ISSUE THREAD

**Issue by stilobique** [YunoHost-Apps/funkwhale_ynh#251]
### Describe the bug

Hello, it's the comeback about this issue :/ . [The previous issue closed are here](https://github.com/YunoHost-Apps/funkwhale_ynh/issues/198). Once again, to solved it, I move the db to force creating a new file.

To give more info, everything worked fine, but there was a power cut, and since then the service has had these problems.
If the error back this week I think try to more investigate. The goal with this topic are to get date feedback, and look if another user have this issue again.

```bash
mv /var/www/funkwhale/api/celerybeat-schedule.db /var/www/funkwhale/api/celerybeat-schedule_old.db

ls -l /var/www/funkwhale/api

-rw-r--r--  1 funkwhale funkwhale  12288 Sep 19 12:52 celerybeat-schedule.db
-rw-r--r--  1 funkwhale funkwhale  12288 Sep 19 12:46 celerybeat-schedule_old.db
drwxr-x---  5 funkwhale www-data    4096 Sep  7 18:35 config
drwxr-x---  2 funkwhale www-data    4096 Sep  7 09:03 docker
-rw-r-----  1 funkwhale www-data    2782 Sep  7 09:03 Dockerfile
drwxr-x--- 26 funkwhale www-data    4096 Sep  7 18:35 funkwhale_api
-rwxr-x---  1 funkwhale www-data    2000 Sep  7 09:03 install_os_dependencies.sh
-rwxr-x---  1 funkwhale www-data     336 Sep  7 09:03 manage.py
-rw-r-----  1 funkwhale www-data  293275 Sep  7 09:03 poetry.lock
-rw-r-----  1 funkwhale www-data    4158 Sep  7 09:03 pyproject.toml
-rw-r-----  1 funkwhale www-data    2550 Sep  7 09:03 Readme.md
```

### Logs
Here, the log about the service.
```journalctl
sept. 19 12:46:08 systemd[1]: Started funkwhale celery beat process.
sept. 19 12:46:11 systemd[1]: funkwhale-beat.service: Main process exited, code=exited, status=1/FAILURE
sept. 19 12:46:11 systemd[1]: funkwhale-beat.service: Failed with result 'exit-code'.
sept. 19 12:46:11 systemd[1]: funkwhale-beat.service: Consumed 2.153s CPU time.
```

``` /var/log/funkwhale/funkwhale-beat.log 
[2023-09-19 10:46:11,094: WARNING/MainProcess]     
[2023-09-19 10:46:11,094: WARNING/MainProcess] super().__init__(*args, **kwargs)
[2023-09-19 10:46:11,094: WARNING/MainProcess]   File "/var/www/funkwhale/venv/lib/python3.9/site-packages/celery/beat.py", line 271, in __init__
[2023-09-19 10:46:11,094: WARNING/MainProcess]     
[2023-09-19 10:46:11,094: WARNING/MainProcess] self.setup_schedule()
[2023-09-19 10:46:11,094: WARNING/MainProcess]   File "/var/www/funkwhale/venv/lib/python3.9/site-packages/celery/beat.py", line 543, in setup_schedule
[2023-09-19 10:46:11,095: WARNING/MainProcess]     
[2023-09-19 10:46:11,095: WARNING/MainProcess] self._create_schedule()
[2023-09-19 10:46:11,095: WARNING/MainProcess]   File "/var/www/funkwhale/venv/lib/python3.9/site-packages/celery/beat.py", line 576, in _create_schedule
[2023-09-19 10:46:11,095: WARNING/MainProcess]     
[2023-09-19 10:46:11,095: WARNING/MainProcess] self._store['entries'] = {}
[2023-09-19 10:46:11,095: WARNING/MainProcess]   File "/usr/lib/python3.9/shelve.py", line 125, in __setitem__
[2023-09-19 10:46:11,095: WARNING/MainProcess]     
[2023-09-19 10:46:11,095: WARNING/MainProcess] self.dict[key.encode(self.keyencoding)] = f.getvalue()
[2023-09-19 10:46:11,095: WARNING/MainProcess] _dbm
[2023-09-19 10:46:11,095: WARNING/MainProcess] .
[2023-09-19 10:46:11,095: WARNING/MainProcess] error
[2023-09-19 10:46:11,095: WARNING/MainProcess] : 
[2023-09-19 10:46:11,095: WARNING/MainProcess] cannot add item to database
[2023-09-19 10:46:11,166: WARNING/MainProcess] Exception ignored in: 
[2023-09-19 10:46:11,166: WARNING/MainProcess] <function Shelf.__del__ at 0x7f815ee3e940>
[2023-09-19 10:46:11,166: WARNING/MainProcess] Traceback (most recent call last):
[2023-09-19 10:46:11,166: WARNING/MainProcess]   File "/usr/lib/python3.9/shelve.py", line 162, in __del__
[2023-09-19 10:46:11,166: WARNING/MainProcess]     
[2023-09-19 10:46:11,166: WARNING/MainProcess] self.close()
[2023-09-19 10:46:11,166: WARNING/MainProcess]   File "/usr/lib/python3.9/shelve.py", line 144, in close
[2023-09-19 10:46:11,166: WARNING/MainProcess]     
[2023-09-19 10:46:11,166: WARNING/MainProcess] self.sync()
[2023-09-19 10:46:11,166: WARNING/MainProcess]   File "/usr/lib/python3.9/shelve.py", line 168, in sync
[2023-09-19 10:46:11,167: WARNING/MainProcess]     
[2023-09-19 10:46:11,167: WARNING/MainProcess] self[key] = entry
[2023-09-19 10:46:11,167: WARNING/MainProcess]   File "/usr/lib/python3.9/shelve.py", line 125, in __setitem__
[2023-09-19 10:46:11,167: WARNING/MainProcess]     
[2023-09-19 10:46:11,167: WARNING/MainProcess] self.dict[key.encode(self.keyencoding)] = f.getvalue()
[2023-09-19 10:46:11,167: WARNING/MainProcess] _dbm
[2023-09-19 10:46:11,167: WARNING/MainProcess] .
[2023-09-19 10:46:11,167: WARNING/MainProcess] error
[2023-09-19 10:46:11,167: WARNING/MainProcess] : 
[2023-09-19 10:46:11,167: WARNING/MainProcess] cannot add item to database
celery beat v5.2.7 (dawn-chorus) is starting.
__    -    ... __   -        _
LocalTime -> 2023-09-19 10:46:11
Configuration ->
    . broker -> redis://127.0.0.1:6379/1
    . loader -> celery.loaders.app.AppLoader
    . scheduler -> celery.beat.PersistentScheduler
    . db -> celerybeat-schedule
    . logfile -> [stderr]@%INFO
    . maxinterval -> 5.00 minutes (300s)
```

**Comment by orhtej2** [comment]
This looks like unresolved upstream issue: https://dev.funkwhale.audio/funkwhale/funkwhale/-/issues/1149
