### ISSUE TITLE
FATAL:  Peer authentication failed for user "funkwhale"

### ISSUE THREAD

**Issue by csolisr** [YunoHost-Apps/funkwhale_ynh#26]
Currently testing on Debian Stretch, latest Yunohost version. Upon trying to install, the attempt fails with the following error message:

    + cd /var/www/funkwhale
    + ynh_psql_execute_as_root 'ALTER USER funkwhale WITH SUPERUSER;'
    + local 'sql=ALTER USER funkwhale WITH SUPERUSER;'
    + sudo --login --user=postgres psql
    ALTER ROLE
    + python api/manage.py migrate
    Traceback (most recent call last):
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
        self.connect()
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 194, in connect
        self.connection = self.get_new_connection(conn_params)
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 168, in get_new_connection
        connection = Database.connect(**conn_params)
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/psycopg2/__init__.py", line 130, in connect
        conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
    psycopg2.OperationalError: FATAL:  Peer authentication failed for user "funkwhale"
    The above exception was the direct cause of the following exception:
    Traceback (most recent call last):
      File "api/manage.py", line 20, in <module>
        execute_from_command_line(sys.argv)
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
        utility.execute()
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
        output = self.handle(*args, **options)
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 79, in handle
        executor = MigrationExecutor(connection, self.migration_progress_callback)
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 18, in __init__
        self.loader = MigrationLoader(self.connection)
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/migrations/loader.py", line 49, in __init__
        self.build_graph()
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/migrations/loader.py", line 207, in build_graph
        self.applied_migrations = recorder.applied_migrations()
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
        if self.has_table():
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/migrations/recorder.py", line 44, in has_table
        return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 255, in cursor
        return self._cursor()
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 232, in _cursor
        self.ensure_connection()
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
        self.connect()
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
        raise dj_exc_value.with_traceback(traceback) from exc_value
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
        self.connect()
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/base/base.py", line 194, in connect
        self.connection = self.get_new_connection(conn_params)
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/postgresql/base.py", line 168, in get_new_connection
        connection = Database.connect(**conn_params)
      File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/psycopg2/__init__.py", line 130, in connect
        conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
    django.db.utils.OperationalError: FATAL:  Peer authentication failed for user "funkwhale"

I have already tried purging postgresql completely with all settings files first.

**Comment by Jibec** [comment]
Thanks for your feedback.
Can you please provide the installation log?

Should be in /var/log/yunohost (api if installed with web admin, CLI if not). Remember to:
. replace password and other data you may find sensitive (like domain and user name) with easy for me to understand replacement
. extract only the log related to funkwhale

**Comment by csolisr** [comment]
Sorry for the delay, I managed to export a full log of the output: http://sebsauvage.net/paste/?22542080663a45b4#4COJUPJvMQ6YJm6uHo7falnuKQAGti+lT3SQaZywbhs=

**Comment by csolisr** [comment]
As the log shows, this is one of several applications installed in my instance, including Nextcloud, Roundcube and Hubzilla among others. It is a x86-64 instance. From what I recall, I haven't installed Postgresql directly, only as a dependency of Funkwhale.

**Comment by csolisr** [comment]
I reattempted to perform the installation with an updated version of YunoHost, and it's still failing as per the following log: https://paste.yunohost.org/raw/sezebeqoki

**Comment by Jibec** [comment]
ok, you can edit the postgres configuration file:

`sudo vim /etc/postgresql/9.6/main/pg_hba.conf`

and replace:

>  local all all peer

with

> local all all password

and it should work as expected.

**Comment by Thovi98** [comment]
Hello @Jibec!
As you were able to understand the issue with `FATAL: Peer authentication failed for user “funkwhale”`, may I ask you to have a look at https://forum.yunohost.org/t/funkwhale-installation-fails/27504, at it seems to be similar? Thanks <3
