### ISSUE TITLE
install fail : could not open extension control file "/usr/share/postgresql/9.6/extension/unaccent.control"

### ISSUE THREAD

**Issue by GannonTdW** [YunoHost-Apps/funkwhale_ynh#33]
Hello,

Je viens de vouloir installer funkwhale sous son propre sous domaine et je rencontre l'erreur suivante :

``` 
DEBUG - + python api/manage.py migrate
WARNING - /bin/sh: BASH_XTRACEFD: 7: invalid value for trace file descriptor
DEBUG - Operations to perform:
WARNING - Traceback (most recent call last):
DEBUG -   Apply all migrations: account, admin, auth, authtoken, common, contenttypes, dynamic_preferences, favorites, federation, history, music, playlists, radios, requests, sessions, sites, socialaccount, taggit, users
WARNING -   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
DEBUG - Running migrations:
WARNING -     return self.cursor.execute(sql, params)
DEBUG -   Applying contenttypes.0001_initial... OK
WARNING - psycopg2.OperationalError: could not open extension control file "/usr/share/postgresql/9.6/extension/unaccent.control": No such file or directory
DEBUG -   Applying contenttypes.0002_remove_content_type_name... OK
WARNING - 
DEBUG -   Applying auth.0001_initial... OK
WARNING - 
DEBUG -   Applying auth.0002_alter_permission_name_max_length... OK
WARNING - The above exception was the direct cause of the following exception:
DEBUG -   Applying auth.0003_alter_user_email_max_length... OK
WARNING - 
DEBUG -   Applying auth.0004_alter_user_username_opts... OK
WARNING - Traceback (most recent call last):
DEBUG -   Applying auth.0005_alter_user_last_login_null... OK
WARNING -   File "api/manage.py", line 20, in <module>
DEBUG -   Applying auth.0006_require_contenttypes_0002... OK
WARNING -     execute_from_command_line(sys.argv)
DEBUG -   Applying users.0001_initial... OK
WARNING -   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
DEBUG -   Applying account.0001_initial... OK
WARNING -     utility.execute()
DEBUG -   Applying account.0002_email_max_length... OK
WARNING -   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
DEBUG -   Applying admin.0001_initial... OK
WARNING -     self.fetch_command(subcommand).run_from_argv(self.argv)
DEBUG -   Applying admin.0002_logentry_remove_auto_add... OK
WARNING -   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
DEBUG -   Applying auth.0007_alter_validators_add_error_messages... OK
WARNING -     self.execute(*args, **cmd_options)
DEBUG -   Applying auth.0008_alter_user_username_max_length... OK
WARNING -   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
DEBUG -   Applying auth.0009_alter_user_last_name_max_length... OK
WARNING -     output = self.handle(*args, **options)
DEBUG -   Applying authtoken.0001_initial... OK
WARNING -   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 200, in handle
DEBUG -   Applying authtoken.0002_auto_20160226_1747... OK
WARNING -     fake_initial=fake_initial,
WARNING -   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 117, in migrate
WARNING -     state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
WARNING -   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
WARNING -     state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
WARNING -   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
WARNING -     state = migration.apply(state, schema_editor)
WARNING -   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/migrations/migration.py", line 122, in apply
WARNING -     operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
WARNING -   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/contrib/postgres/operations.py", line 19, in database_forwards
WARNING -     schema_editor.execute("CREATE EXTENSION IF NOT EXISTS %s" % schema_editor.quote_name(self.name))
WARNING -   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/base/schema.py", line 133, in execute
WARNING -     cursor.execute(sql, params)
WARNING -   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
WARNING -     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
WARNING -   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
WARNING -     return executor(sql, params, many, context)
WARNING -   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
WARNING -     return self.cursor.execute(sql, params)
WARNING -   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
WARNING -     raise dj_exc_value.with_traceback(traceback) from exc_value
WARNING -   File "/var/www/funkwhale/virtualenv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
WARNING -     return self.cursor.execute(sql, params)
WARNING - django.db.utils.OperationalError: could not open extension control file "/usr/share/postgresql/9.6/extension/unaccent.control": No such file or directory
WARNING - 
DEBUG -   Applying common.0001_initial...+ ynh_exit_properly

```
Je ne comprend pas la fonction de ce fichier, le seul lien que je trouve est [ici](https://www.apt-browse.org/browse/debian/stretch/main/i386/postgresql-contrib-9.6/9.6.7-0+deb9u1/file/usr/share/postgresql/9.6/extension/unaccent.control)
Mais "unaccent", ca serait lié à des problèmes d'encodage, ou pour enlever les accents dans la bd ? -_-"
Je remarque que mon istallation plante au même endroit que csolisr mais pas pour la même raison.
-_-"

Info sur mon Yunohost : 

```
OS
    Debian 9.5 64bit (Linux 4.9.0-8-amd64)
yunohost
    3.2.0 (stable)
yunohost-admin
    3.2.0 (stable)
moulinette
    3.2.0 (stable)
ssowat
    3.2.0 (stable)
```
 
 
Vous pouvez trouver les logs complets [ICI](https://paste.yunohost.org/raw/ebuvetanin)

Merci par avance.

**Comment by EliotBerriot** [comment]
@GannonTdW je suis un peu à la bourre sur ce coup là. Unaccent est une extension PostgreSQL (le moteur de base de données utilisé par Funkwhale) pour avoir une recherche plus efficace. Donc ce n'est pas pour enlever les accents ou lié à un problème d'encodage, mais cela fournit certaines fonctions de recherches utilisées par l'application.

Pour la cause du problème par contre, je ne sais vraiment pas :/

**Comment by GannonTdW** [comment]
@EliotBerriot 

Je n'avais pas vu ton message mais je viens de résoudre le problème en installant `postgresql-contrib`
J'ai créé un pull requests [ici](https://github.com/YunoHost-Apps/funkwhale_ynh/commit/feae5c6f2d4731903a250d9ce0e5e449fd4ca27f)
(je comprend pas la modif à la ligne 245, j'y ai pas touché pourtant ...)
