### ISSUE TITLE
Upgrade to 0.17 failed

### ISSUE THREAD

**Issue by MyNameIsTroll** [YunoHost-Apps/funkwhale_ynh#43]
Bonjour @Jibec merci pour la mise a jour ^^
Malheureusement l'update a échoué chez moi en essayant depuis l'interface d'administration de yunohost de la v0.16.3 > 0.17 

Voici mes logs:
```
2018-10-25 12:27:47,076: WARNING - mv: cannot stat '/var/www/funkwhale/!(code)': No such file or directory
2018-10-25 12:27:47,081: WARNING - mv: cannot stat '/var/www/funkwhale/code/data/media': No such file or directory
2018-10-25 12:27:47,084: WARNING - mv: cannot stat '/var/www/funkwhale/code/data/music': No such file or directory
2018-10-25 12:27:51,700: WARNING - The output directory is not empty
2018-10-25 12:27:51,803: WARNING - Backup failed, the upgrade process was aborted.
2018-10-25 12:27:51,945: ERROR - Impossible de mettre à jour funkwhale
```

J'ai ensuite désinstallé la v0.16.3 et réinstallé a neuf la v0.17 et là tout s'est bien passé, voici les logs:

```
2018-10-25 12:55:21,739: WARNING - debconf: unable to initialize frontend: Dialog
2018-10-25 12:55:21,759: WARNING - debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
2018-10-25 12:55:21,761: WARNING - debconf: falling back to frontend: Readline
2018-10-25 12:55:21,863: WARNING - debconf: unable to initialize frontend: Readline
2018-10-25 12:55:21,865: WARNING - debconf: (This frontend requires a controlling tty.)
2018-10-25 12:55:21,867: WARNING - debconf: falling back to frontend: Teletype
2018-10-25 12:55:21,869: WARNING - dpkg-preconfigure: unable to re-open stdin:
2018-10-25 12:55:39,636: WARNING - 2018-10-25 12:55:39 URL:https://code.eliotberriot.com/funkwhale/funkwhale/-/archive/0.17/funkwhale-0.17.tar.bz2 [10818181/10818181] -> "app.tar.bz2" [1]
2018-10-25 12:55:46,461: WARNING - 2018-10-25 12:55:46 URL:https://code.eliotberriot.com/funkwhale/funkwhale/-/jobs/11162/artifacts/download [2960426/2960426] -> "app-frontend.zip" [1]
2018-10-25 12:56:22,586: WARNING - Cache entry deserialization failed, entry ignored
2018-10-25 12:56:23,390: WARNING - Cache entry deserialization failed, entry ignored
2018-10-25 13:01:11,388: WARNING - Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x75b75420>
2018-10-25 13:01:11,459: WARNING - Traceback (most recent call last):
2018-10-25 13:01:11,461: WARNING -   File "/usr/lib/python3.5/weakref.py", line 117, in remove
2018-10-25 13:01:11,464: WARNING - TypeError: 'NoneType' object is not callable
2018-10-25 13:01:11,466: WARNING - Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x75b75420>
2018-10-25 13:01:11,468: WARNING - Traceback (most recent call last):
2018-10-25 13:01:11,470: WARNING -   File "/usr/lib/python3.5/weakref.py", line 117, in remove
2018-10-25 13:01:11,472: WARNING - TypeError: 'NoneType' object is not callable
2018-10-25 13:01:22,620: WARNING - Created symlink /etc/systemd/system/multi-user.target.wants/funkwhale-server.service → /etc/systemd/system/funkwhale-server.service.
2018-10-25 13:01:28,946: WARNING - Created symlink /etc/systemd/system/multi-user.target.wants/funkwhale-worker.service → /etc/systemd/system/funkwhale-worker.service.
2018-10-25 13:01:32,863: WARNING - Created symlink /etc/systemd/system/multi-user.target.wants/funkwhale-beat.service → /etc/systemd/system/funkwhale-beat.service.
2018-10-25 13:01:39,656: SUCCESS - La configuration de SSOwat a été générée
2018-10-25 13:01:39,659: SUCCESS - Installation terminée
```

**Comment by Jibec** [comment]
OK, donc c'est un demi-succès ;) Je regarde ce soir, la sauvegarde doit donc être améliorée !

**Comment by Jibec** [comment]
Fixed by https://github.com/YunoHost-Apps/funkwhale_ynh/pull/45

thanks for reporting!
