### ISSUE TITLE
Update impossible due to backup failure

### ISSUE THREAD

**Issue by MyNameIsTroll** [YunoHost-Apps/funkwhale_ynh#59]
Hi @Jibec ,
I have a problem when I try to update the application from version 0.17 to version 0.18 via the yunohost web page, the installation stops with these lines in the logs:

```
2019-01-29 11:16:14,048: WARNING - The output directory is not empty
2019-01-29 11:16:14,152: WARNING - Backup failed, the upgrade process was aborted.
2019-01-29 11:16:14,277: ERROR - Impossible de mettre à jour funkwhale
```

**Comment by MyNameIsTroll** [comment]
J'ai galléré un peu a trouver les logs, il y a pleins de fichiers ^^ ...
j'ai trouvé ceci dans  **/var/log/yunohost/yunohost-api.log**
mais j'ai pas l'impression qu'il y ait plus d'informations qu'avant.

```
2019-01-29 11:15:53,890 INFO     yunohost.app app_upgrade - [654.68] Upgrading apps funkwhale
2019-01-29 11:15:53,892 INFO     yunohost.app app_upgrade - [654.68] Mise à jour de l’application funkwhale...
2019-01-29 11:16:14,048 WARNING  yunohost.hook <lambda> - [654.68] The output directory is not empty
2019-01-29 11:16:14,152 WARNING  yunohost.hook <lambda> - [654.68] Backup failed, the upgrade process was aborted.
2019-01-29 11:16:14,277 ERROR    yunohost.app app_upgrade - [654.68] Impossible de mettre à jour funkwhale
2019-01-29 11:16:14,287 INFO     yunohost.log close - [654.68] <strong>L’opération  « Mettre à jour l’application « funkwhale » » a échouée ! Pour avoir de l’aide, merci <a href="#/tools/logs/20190129-111557-ap$
2019-01-29 11:16:14,304 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2019-01-29 11:16:14] "PUT /upgrade/apps?app=funkwhale HTTP/1.1" 500 171 21.691863
2019-01-29 11:16:19,714 INFO     moulinette.actionsmap process - processing action [654.69]: yunohost.log.display
2019-01-29 11:16:19,790 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2019-01-29 11:16:19] "GET /logs/display?path=20190129-111557-app_upgrade-funkwhale&number=50&locale=fr HTTP/1.1" 200 1208 0.$
2019-01-29 11:20:19,955 INFO     moulinette.actionsmap process - processing action [654.70]: yunohost.app.upgrade
2019-01-29 11:20:21,107 INFO     yunohost.app app_upgrade - [654.70] Upgrading apps funkwhale
2019-01-29 11:20:21,110 INFO     yunohost.app app_upgrade - [654.70] Mise à jour de l’application funkwhale...
2019-01-29 11:20:41,468 ERROR    yunohost.app _fetch_app_from_git - [654.70] unable to download https://github.com/YunoHost-Apps/funkwhale_ynh/archive/8b7b3f0806c9f3600a0900bcae8e9f25a3e29f91.zip
Traceback (most recent call last):
  File "/usr/lib/moulinette/yunohost/app.py", line 1943, in _fetch_app_from_git
    'wget', '-qO', app_tmp_archive, tarball_url])
  File "/usr/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['wget', '-qO', '/var/cache/yunohost/from_file.zip', 'https://github.com/YunoHost-Apps/funkwhale_ynh/archive/8b7b3f0806c9f3600a0900bcae8e9f25a3e29f91.zip']' returned non-zero exit s$
2019-01-29 11:20:41,570 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2019-01-29 11:20:41] "PUT /upgrade/apps?app=funkwhale HTTP/1.1" 500 181 21.800987
2019-01-29 11:27:34,537 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2019-01-29 11:27:34] "GET /version?locale=fr HTTP/1.1" 200 355 1.190972
2019-01-29 11:27:36,061 INFO     moulinette.actionsmap process - processing action [654.71]: yunohost.app.upgrade
2019-01-29 11:27:37,147 INFO     yunohost.app app_upgrade - [654.71] Upgrading apps funkwhale
2019-01-29 11:27:37,149 INFO     yunohost.app app_upgrade - [654.71] Mise à jour de l’application funkwhale...
2019-01-29 11:28:00,994 WARNING  yunohost.hook <lambda> - [654.71] The output directory is not empty
2019-01-29 11:28:01,099 WARNING  yunohost.hook <lambda> - [654.71] Backup failed, the upgrade process was aborted.
2019-01-29 11:28:01,215 ERROR    yunohost.app app_upgrade - [654.71] Impossible de mettre à jour funkwhale
2019-01-29 11:28:01,217 INFO     yunohost.log close - [654.71] <strong>L’opération  « Mettre à jour l’application « funkwhale » » a échouée ! Pour avoir de l’aide, merci <a href="#/tools/logs/20190129-112744-ap$
2019-01-29 11:28:01,235 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2019-01-29 11:28:01] "PUT /upgrade/apps?app=funkwhale HTTP/1.1" 500 171 25.329325
2019-01-29 11:30:55,634 INFO     moulinette.actionsmap process - processing action [654.72]: yunohost.log.display
2019-01-29 11:30:55,671 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2019-01-29 11:30:55] "GET /logs/display?path=20190129-112744-app_upgrade-funkwhale&number=50&locale=fr HTTP/1.1" 200 1208 0.$
2019-01-29 11:31:14,081 INFO     moulinette.actionsmap process - processing action [654.73]: yunohost.log.list
2019-01-29 11:31:14,195 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2019-01-29 11:31:14] "GET /logs?locale=fr HTTP/1.1" 200 68853 0.342591
2019-01-29 11:31:18,247 INFO     moulinette.actionsmap process - processing action [654.74]: yunohost.log.display
2019-01-29 11:31:18,344 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2019-01-29 11:31:18] "GET /logs/display?path=20190126-234934-app_upgrade-funkwhale&number=50&locale=fr HTTP/1.1" 200 1208 0.$
2019-01-29 11:31:21,236 INFO     moulinette.actionsmap process - processing action [654.75]: yunohost.log.list
2019-01-29 11:31:21,324 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2019-01-29 11:31:21] "GET /logs?locale=fr HTTP/1.1" 200 68853 0.224852
2019-01-29 11:31:22,918 INFO     moulinette.actionsmap process - processing action [654.76]: yunohost.log.display
2019-01-29 11:31:22,940 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2019-01-29 11:31:22] "GET /logs/display?path=20190129-111557-app_upgrade-funkwhale&number=50&locale=fr HTTP/1.1" 200 1208 0.$
2019-01-29 11:31:25,616 INFO     moulinette.actionsmap process - processing action [654.77]: yunohost.log.list
2019-01-29 11:31:25,705 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2019-01-29 11:31:25] "GET /logs?locale=fr HTTP/1.1" 200 68853 0.220564
2019-01-29 11:31:27,015 INFO     moulinette.actionsmap process - processing action [654.78]: yunohost.log.display
2019-01-29 11:31:27,037 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2019-01-29 11:31:27] "GET /logs/display?path=20190129-112744-app_upgrade-funkwhale&number=50&locale=fr HTTP/1.1" 200 1208 0.$
2019-01-29 11:31:28,961 INFO     moulinette.actionsmap process - processing action [654.79]: yunohost.log.list
2019-01-29 11:31:29,051 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2019-01-29 11:31:29] "GET /logs?locale=fr HTTP/1.1" 200 68853 0.230541
2019-01-29 11:34:02,319 INFO     moulinette.actionsmap process - processing action [654.80]: yunohost.user.list
2019-01-29 11:34:02,322 INFO     geventwebsocket.handler log_request - 127.0.0.1 - - [2019-01-29 11:34:02] "GET /users?locale=fr HTTP/1.1" 200 313 0.146732
2019-01-29 11:34:02,795 INFO     moulinette.actionsmap process - processing action [654.81]: yunohost.tools.diagnosis

```

**Comment by Jibec** [comment]
hum, là c'est le backup qui échoue donc dans le doute il ne touche à rien, je vais essayer de reproduire

**Comment by Jibec** [comment]
vu ensemble, il fallait supprimer le fichier temporaire du backup puis relancer
le problème source est ici: https://github.com/YunoHost/issues/issues/1308
