### ISSUE TITLE
Error during the installation

### ISSUE THREAD

**Issue by JOduMonT** [YunoHost-Apps/funkwhale_ynh#97]
If I understood well the error is related to unicode-slugify

> My Yunohost run inside a non privileged LXC (Proxmox) on top of Debian 9 (amd64)

```
2020-01-27 17:46:19,902: DEBUG - Collecting unicode-slugify
2020-01-27 17:46:19,902: DEBUG -   Downloading unicode-slugify-0.1.3.tar.gz (4.4 kB)
2020-01-27 17:46:20,103: WARNING -     ERROR: Command errored out with exit status 1:
2020-01-27 17:46:20,103: WARNING -      command: /var/www/funkwhale/code/virtualenv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-06ceygz1/unicode-slugify/setup.py'"'"'; __file__='"'"'/tmp/pip-install-06ceygz1/unicode-slugify/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-06ceygz1/unicode-slugify/pip-egg-info
2020-01-27 17:46:20,103: WARNING -          cwd: /tmp/pip-install-06ceygz1/unicode-slugify/
2020-01-27 17:46:20,103: WARNING -     Complete output (7 lines):
2020-01-27 17:46:20,104: WARNING -     Traceback (most recent call last):
2020-01-27 17:46:20,104: WARNING -       File "<string>", line 1, in <module>
2020-01-27 17:46:20,104: WARNING -       File "/tmp/pip-install-06ceygz1/unicode-slugify/setup.py", line 7, in <module>
2020-01-27 17:46:20,104: WARNING -         long_description=open('README.md').read(),
2020-01-27 17:46:20,104: WARNING -       File "/var/www/funkwhale/code/virtualenv/lib/python3.5/encodings/ascii.py", line 26, in decode
2020-01-27 17:46:20,104: WARNING -         return codecs.ascii_decode(input, self.errors)[0]
2020-01-27 17:46:20,105: WARNING -     UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 361: ordinal not in range(128)
2020-01-27 17:46:20,105: WARNING -     ----------------------------------------
2020-01-27 17:46:20,606: DEBUG - + ynh_exit_properly
2020-01-27 17:46:20,607: WARNING - ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
2020-01-27 17:46:20,607: DEBUG - + local exit_code=1
2020-01-27 17:46:20,607: DEBUG - + '[' 1 -eq 0 ']'
2020-01-27 17:46:20,607: DEBUG - + trap '' EXIT

```

**Comment by Sporiff** [comment]
Interestingly I experienced the same and it went away when I tried to install again. My assumption here is that it's to do with locale settings on the server (this triggers the warning). The package does actually install correctly, but the warning causes it to give a non-0 error code which the script interprets as a failure. Were you able to install after this?

**Comment by JOduMonT** [comment]
@Sporiff sadly I wiped my yunohost LXC for other reason but
in any LXC I do this for my locale
```

export LANGUAGE=en_US.UTF-8
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

[[ -z "$(grep LC_ALL /etc/bash.bashrc)" ]] && \
cat <<EOF >> /etc/bash.bashrc
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export LANGUAGE="en_US:en"
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
EOF

locale-gen --purge en_US.UTF-8
localedef -i en_US -f UTF-8 en_US.UTF-8

sed -i '/^LANG=/d' /etc/default/locale
echo -e 'LANG="en_US.UTF-8"\nLANGUAGE="en_US:en"\n' > /etc/default/locale
```

however I do not reboot before installing yunohost
